FROM node:22-alpine3.19 AS development

# environment
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 20.12.2
ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

RUN mkdir /apollus
WORKDIR /apollus
COPY ../app /apollus

# ubuntu apps
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y curl
RUN apt-get install wget bash -y
RUN apt-get install python3 -y

# setup node js
RUN mkdir /usr/local/nvm
RUN touch ~/.bashrc && chmod +x ~/.bashrc
RUN curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash \
    && . "$NVM_DIR/nvm.sh" \
    && nvm install 20.12.2 \
    && nvm use 20.12.2

#install dependencies
RUN npm install -g npm@10.6.0 \
    && npm install

CMD npm install && npm run dev
